import { Badge, Checkbox, Input, Label, Separator, SheetContent, SheetHeader, SheetTitle } from "@/components/ui"
import { useMediaQuery } from "@/hooks"
import { CheckedState } from "@radix-ui/react-checkbox"
import { useEffect, useState } from "react"
import { useQueryClient } from "react-query"

interface Props {
	language:
		| {
				name: string
				key: string
				count: number
		  }
		| undefined
	setLanguage: React.Dispatch<
		React.SetStateAction<
			| {
					name: string
					key: string
					count: number
			  }
			| undefined
		>
	>
	setLanguagesVisible: React.Dispatch<React.SetStateAction<boolean>>
}

export function BookSearchLanguages({ language, setLanguage, setLanguagesVisible }: Props) {
	const isVertical = useMediaQuery("(max-width: 768px)")
	const [filterText, setFilterText] = useState("")

	return (
		<SheetContent className={`max-w-xl md:max-w-xl space-y-4 ${isVertical && "w-full"} overflow-scroll`}>
			<SheetHeader>
				<SheetTitle>languages</SheetTitle>
			</SheetHeader>
			<Separator />
			<Input
				type="text"
				placeholder="filter..."
				showCharacterCount={false}
				value={filterText}
				onChange={(e) => setFilterText(e.target.value)}
			/>
			{languageList
				.filter(
					(lang) =>
						!filterText ||
						language?.name.toLowerCase().includes(filterText.toLowerCase()) ||
						language?.key.toLowerCase().includes(filterText.toLowerCase())
				)
				.map((lang) => {
					const isChecked = language === lang
					const handleCheck = (checked: CheckedState) => {
						if (checked) {
							setLanguage(lang)
							setLanguagesVisible(false)
						} else {
							setLanguage(undefined)
						}
					}

					return (
						<Badge variant={isChecked ? "default" : "secondary"} key={lang.key} className="mr-2">
							<Checkbox
								hidden
								id={lang.name}
								defaultChecked={isChecked}
								checked={isChecked}
								onCheckedChange={handleCheck}
							/>
							<Label className="hover:cursor-pointer" htmlFor={lang.name}>
								{lang.name}
							</Label>
						</Badge>
					)
				})}
		</SheetContent>
	)
}

const languageList = [
	{ name: "English", key: "/languages/eng", count: 18615100 },
	{ name: "German", key: "/languages/ger", count: 2261334 },
	{ name: "French", key: "/languages/fre", count: 1801062 },
	{ name: "Spanish", key: "/languages/spa", count: 1432816 },
	{ name: "Russian", key: "/languages/rus", count: 756499 },
	{ name: "Italian", key: "/languages/ita", count: 716829 },
	{ name: "Chinese", key: "/languages/chi", count: 685902 },
	{ name: "Japanese", key: "/languages/jpn", count: 502364 },
	{ name: "Arabic", key: "/languages/ara", count: 339969 },
	{ name: "Portuguese", key: "/languages/por", count: 318991 },
	{ name: "Hebrew", key: "/languages/heb", count: 230450 },
	{ name: "Korean", key: "/languages/kor", count: 210098 },
	{ name: "Polish", key: "/languages/pol", count: 198458 },
	{ name: "Dutch", key: "/languages/dut", count: 180657 },
	{ name: "Latin", key: "/languages/lat", count: 148188 },
	{ name: "Indonesian", key: "/languages/ind", count: 129877 },
	{ name: "Swedish", key: "/languages/swe", count: 90084 },
	{ name: "Undetermined", key: "/languages/und", count: 88344 },
	{ name: "Turkish", key: "/languages/tur", count: 86994 },
	{ name: "Hungarian", key: "/languages/hun", count: 83261 },
	{ name: "Urdu", key: "/languages/urd", count: 77585 },
	{ name: "Hindi", key: "/languages/hin", count: 77319 },
	{ name: "Mandarin", key: "/languages/cmn", count: 75718 },
	{ name: "Danish", key: "/languages/dan", count: 75615 },
	{ name: "Persian", key: "/languages/per", count: 73209 },
	{ name: "Czech", key: "/languages/cze", count: 71813 },
	{ name: "Ukrainian", key: "/languages/ukr", count: 69743 },
	{ name: "Modern Greek", key: "/languages/gre", count: 60237 },
	{ name: "Romanian", key: "/languages/rum", count: 51307 },
	{ name: "Bulgarian", key: "/languages/bul", count: 50473 },
	{ name: "Vietnamese", key: "/languages/vie", count: 47946 },
	{ name: "Catalan", key: "/languages/cat", count: 43492 },
	{ name: "Bengali", key: "/languages/ben", count: 42302 },
	{ name: "Norwegian", key: "/languages/nor", count: 40426 },
	{ name: "Thai", key: "/languages/tha", count: 39533 },
	{ name: "Croatian", key: "/languages/hrv", count: 39260 },
	{ name: "Finnish", key: "/languages/fin", count: 38298 },
	{ name: "Serbian", key: "/languages/srp", count: 36778 },
	{ name: "Yiddish", key: "/languages/yid", count: 31591 },
	{ name: "Tamil", key: "/languages/tam", count: 31490 },
	{ name: "Multiple languages", key: "/languages/mul", count: 31264 },
	{ name: "Tibetan", key: "/languages/tib", count: 26773 },
	{ name: "Gujarati", key: "/languages/guj", count: 23588 },
	{ name: "Armenian", key: "/languages/arm", count: 22614 },
	{ name: "Marathi", key: "/languages/mar", count: 22182 },
	{ name: "Welsh", key: "/languages/wel", count: 21534 },
	{ name: "Punjabi", key: "/languages/pan", count: 20679 },
	{ name: "Slovak", key: "/languages/slo", count: 18144 },
	{ name: "Telugu", key: "/languages/tel", count: 18086 },
	{ name: "Malay", key: "/languages/may", count: 17084 },
	{ name: "Kannada", key: "/languages/kan", count: 16667 },
	{ name: "Sanskrit", key: "/languages/san", count: 16378 },
	{ name: "Slovene", key: "/languages/slv", count: 15728 },
	{ name: "Malayalam", key: "/languages/mal", count: 14071 },
	{ name: "Albanian", key: "/languages/alb", count: 13738 },
	{ name: "Burmese", key: "/languages/bur", count: 13244 },
	{ name: "Lithuanian", key: "/languages/lit", count: 12947 },
	{ name: "Latvian", key: "/languages/lav", count: 12499 },
	{ name: "Georgian", key: "/languages/geo", count: 12226 },
	{ name: "Afrikaans", key: "/languages/afr", count: 11403 },
	{ name: "Nepali", key: "/languages/nep", count: 11156 },
	{ name: "Estonian", key: "/languages/est", count: 10650 },
	{ name: "Macedonian", key: "/languages/mac", count: 10590 },
	{ name: "Mongolian", key: "/languages/mon", count: 10263 },
	{ name: "Ancient Greek", key: "/languages/grc", count: 9822 },
	{ name: "Odia", key: "/languages/ori", count: 9356 },
	{ name: "Germanic (Other)", key: "/languages/gem", count: 9212 },
	{ name: "Belarusian", key: "/languages/bel", count: 8751 },
	{ name: "Azerbaijani", key: "/languages/aze", count: 8681 },
	{ name: "Irish", key: "/languages/gle", count: 8563 },
	{ name: "Uzbek", key: "/languages/uzb", count: 8520 },
	{ name: "Icelandic", key: "/languages/ice", count: 7977 },
	{ name: "Sinhala", key: "/languages/sin", count: 7760 },
	{ name: "Kazakh", key: "/languages/kaz", count: 6753 },
	{ name: "Kurdish", key: "/languages/kur", count: 6530 },
	{ name: "Sindhi", key: "/languages/snd", count: 5977 },
	{ name: "Turkish, Ottoman", key: "/languages/ota", count: 5802 },
	{ name: "Galician", key: "/languages/glg", count: 5552 },
	{ name: "Bosnian", key: "/languages/bos", count: 5408 },
	{ name: "Pashto", key: "/languages/pus", count: 5363 },
	{ name: "Kyrgyz", key: "/languages/kir", count: 3742 },
	{ name: "Assamese", key: "/languages/asm", count: 3658 },
	{ name: "Amharic", key: "/languages/amh", count: 3647 },
	{ name: "Tajik", key: "/languages/tgk", count: 3363 },
	{ name: "Swahili", key: "/languages/swa", count: 3313 },
	{ name: "Tagalog", key: "/languages/tgl", count: 2772 },
	{ name: "Tatar", key: "/languages/tat", count: 2735 },
	{ name: "Basque", key: "/languages/baq", count: 2618 },
	{ name: "Scottish Gaelic", key: "/languages/gla", count: 2353 },
	{ name: "Altaic (Other)", key: "/languages/tut", count: 2255 },
	{ name: "Turkmen", key: "/languages/tuk", count: 2094 },
	{ name: "Bashkir", key: "/languages/bak", count: 1985 },
	{ name: "Khmer", key: "/languages/khm", count: 1845 },
	{ name: "Bokm\u00e5l", key: "/languages/nob", count: 1794 },
	{ name: "Javanese", key: "/languages/jav", count: 1767 },
	{ name: "Chuvash", key: "/languages/chv", count: 1674 },
	{ name: "Rajasthani", key: "/languages/raj", count: 1618 },
	{ name: "Finno-Ugrian (Other)", key: "/languages/fiu", count: 1578 },
	{ name: "Lao", key: "/languages/lao", count: 1564 },
	{ name: "Hausa", key: "/languages/hau", count: 1411 },
	{ name: "Romansh", key: "/languages/roh", count: 1399 },
	{ name: "Caucasian (Other)", key: "/languages/cau", count: 1277 },
	{ name: "Pali", key: "/languages/pli", count: 1213 },
	{ name: "Maithili", key: "/languages/mai", count: 1180 },
	{ name: "English, Middle (1100-1500)", key: "/languages/enm", count: 1153 },
	{ name: "Konkani ", key: "/languages/kok", count: 1120 },
	{ name: "Newari", key: "/languages/new", count: 1096 },
	{ name: "Esperanto", key: "/languages/epo", count: 1092 },
	{ name: "Sino-Tibetan (Other)", key: "/languages/sit", count: 1078 },
	{ name: "Niger-Kordofanian (Other)", key: "/languages/nic", count: 1056 },
	{ name: "French, Middle (ca. 1300-1600)", key: "/languages/frm", count: 1038 },
	{ name: "Indic (Other)", key: "/languages/inc", count: 1024 },
	{ name: "Syriac, Modern", key: "/languages/syr", count: 1022 },
	{ name: "Austronesian (Other)", key: "/languages/map", count: 989 },
	{ name: "Croatian", key: "/languages/scr", count: 970 },
	{ name: "Maltese", key: "/languages/mlt", count: 900 },
	{ name: "West Frisian", key: "/languages/fry", count: 841 },
	{ name: "French, Old (ca. 842-1300)", key: "/languages/fro", count: 797 },
	{ name: "Malagasy", key: "/languages/mlg", count: 786 },
	{ name: "Church Slavonic", key: "/languages/chu", count: 778 },
	{ name: "Yoruba", key: "/languages/yor", count: 775 },
	{ name: "Faroese", key: "/languages/fao", count: 760 },
	{ name: "Sorbian (Other)", key: "/languages/wen", count: 732 },
	{ name: "Sundanese", key: "/languages/sun", count: 718 },
	{ name: "Uyghur", key: "/languages/uig", count: 708 },
	{ name: "Somali", key: "/languages/som", count: 698 },
	{ name: "Baluchi", key: "/languages/bal", count: 697 },
	{ name: "Romance (Other)", key: "/languages/roa", count: 690 },
	{ name: "Breton", key: "/languages/bre", count: 682 },
	{ name: "German, Middle High (ca. 1050-1500)", key: "/languages/gmh", count: 682 },
	{ name: "Tigrinya", key: "/languages/tir", count: 682 },
	{ name: "Manipuri", key: "/languages/mni", count: 655 },
	{ name: "Balinese", key: "/languages/ban", count: 652 },
	{ name: "Dravidian (Other)", key: "/languages/dra", count: 649 },
	{ name: "Occitan", key: "/languages/oci", count: 617 },
	{ name: "Serbian", key: "/languages/scc", count: 608 },
	{ name: "Ladino", key: "/languages/lad", count: 592 },
	{ name: "Bhojpuri", key: "/languages/bho", count: 583 },
	{ name: "Zulu", key: "/languages/zul", count: 582 },
	{ name: "Ossetian", key: "/languages/oss", count: 563 },
	{ name: "Braj", key: "/languages/bra", count: 560 },
	{ name: "Yakut", key: "/languages/sah", count: 553 },
	{ name: "Lahnd\u0101", key: "/languages/lah", count: 551 },
	{ name: "Shona", key: "/languages/sna", count: 542 },
	{ name: "Papuan (Other)", key: "/languages/paa", count: 533 },
	{ name: "Kashmiri", key: "/languages/kas", count: 528 },
	{ name: "Prakrit languages", key: "/languages/pra", count: 525 },
	{ name: "Xhosa", key: "/languages/xho", count: 499 },
	{ name: "Mayan languages", key: "/languages/myn", count: 483 },
	{ name: "Creoles and Pidgins, French-based (Other)", key: "/languages/cpf", count: 476 },
	{ name: "Bantu (Other)", key: "/languages/bnt", count: 473 },
	{ name: "Kinyarwanda", key: "/languages/kin", count: 470 },
	{ name: "Egyptian", key: "/languages/egy", count: 459 },
	{ name: "Slavic (Other)", key: "/languages/sla", count: 456 },
	{ name: "Sesotho", key: "/languages/sot", count: 453 },
	{ name: "Dogri", key: "/languages/doi", count: 450 },
	{ name: "South American Indian (Other)", key: "/languages/sai", count: 432 },
	{ name: "English, Old (ca. 450-1100)", key: "/languages/ang", count: 430 },
	{ name: "Judeo-Arabic", key: "/languages/jrb", count: 410 },
	{ name: "Tswana", key: "/languages/tsn", count: 403 },
	{ name: "Romani", key: "/languages/rom", count: 387 },
	{ name: "Irish", key: "/languages/iri", count: 365 },
	{ name: "Proven\u00e7al (to 1500)", key: "/languages/pro", count: 359 },
	{ name: "Scots", key: "/languages/sco", count: 356 },
	{ name: "Lushai", key: "/languages/lus", count: 346 },
	{ name: "Haitian Creole", key: "/languages/hat", count: 344 },
	{ name: "Maldivian", key: "/languages/div", count: 334 },
	{ name: "Northern Sotho", key: "/languages/nso", count: 311 },
	{ name: "Fula", key: "/languages/ful", count: 307 },
	{ name: "Nynorsk", key: "/languages/nno", count: 306 },
	{ name: "Berber (Other)", key: "/languages/ber", count: 304 },
	{ name: "Luxembourgish", key: "/languages/ltz", count: 302 },
	{ name: "Akkadian", key: "/languages/akk", count: 300 },
	{ name: "Chechen", key: "/languages/che", count: 278 },
	{ name: "Serbo-Croatian", key: "/languages/hbs", count: 264 },
	{ name: "Aramaic", key: "/languages/arc", count: 257 },
	{ name: "Wolof", key: "/languages/wol", count: 257 },
	{ name: "Miscellaneous languages", key: "/languages/mis", count: 256 },
	{ name: "Ethiopic", key: "/languages/gez", count: 255 },
	{ name: "Udmurt ", key: "/languages/udm", count: 247 },
	{ name: "Quechua", key: "/languages/que", count: 246 },
	{ name: "Khasi", key: "/languages/kha", count: 244 },
	{ name: "Corsican", key: "/languages/cos", count: 241 },
	{ name: "Kara-Kalpak", key: "/languages/kaa", count: 238 },
	{ name: "Luganda", key: "/languages/lug", count: 238 },
	{ name: "Coptic", key: "/languages/cop", count: 236 },
	{ name: "Mari", key: "/languages/chm", count: 221 },
	{ name: "Papiamento", key: "/languages/pap", count: 220 },
	{ name: "Swazi", key: "/languages/ssw", count: 212 },
	{ name: "Oromo", key: "/languages/orm", count: 205 },
	{ name: "Chewa", key: "/languages/nya", count: 201 },
	{ name: "Igbo", key: "/languages/ibo", count: 199 },
	{ name: "Adygei", key: "/languages/ady", count: 195 },
	{ name: "Northern Ndebele", key: "/languages/nde", count: 195 },
	{ name: "Philippine (Other)", key: "/languages/phi", count: 193 },
	{ name: "Cree", key: "/languages/cre", count: 183 },
	{ name: "Hawaiian", key: "/languages/haw", count: 181 },
	{ name: "Central American Indian (Other)", key: "/languages/cai", count: 176 },
	{ name: "Komi", key: "/languages/kom", count: 171 },
	{ name: "Buriat", key: "/languages/bua", count: 169 },
	{ name: "Pahlavi", key: "/languages/pal", count: 168 },
	{ name: "Creoles and Pidgins (Other)", key: "/languages/crp", count: 167 },
	{ name: "Tsonga", key: "/languages/tso", count: 167 },
	{ name: "M\u0101ori", key: "/languages/mao", count: 165 },
	{ name: "Twi", key: "/languages/twi", count: 164 },
	{ name: "Ojibwe", key: "/languages/oji", count: 160 },
	{ name: "Nahuatl", key: "/languages/nah", count: 159 },
	{ name: "North American Indian (Other)", key: "/languages/nai", count: 158 },
	{ name: "Nilo-Saharan (Other)", key: "/languages/ssa", count: 158 },
	{ name: "Venda", key: "/languages/ven", count: 157 },
	{ name: "Avaric", key: "/languages/ava", count: 155 },
	{ name: "Guarani", key: "/languages/grn", count: 155 },
	{ name: "Inuit-Yupik-Unangan languages", key: "/languages/esk", count: 151 },
	{ name: "Dzongkha", key: "/languages/dzo", count: 146 },
	{ name: "Awadhi ", key: "/languages/awa", count: 144 },
	{ name: "Magahi", key: "/languages/mag", count: 142 },
	{ name: "Inuktitut", key: "/languages/iku", count: 135 },
	{ name: "Sardinian", key: "/languages/srd", count: 135 },
	{ name: "Bambara", key: "/languages/bam", count: 132 },
	{ name: "Kabardian", key: "/languages/kbd", count: 131 },
	{ name: "Marwari", key: "/languages/mwr", count: 125 },
	{ name: "Cornish", key: "/languages/cor", count: 124 },
	{ name: "Mandingo", key: "/languages/man", count: 123 },
	{ name: "Tetum", key: "/languages/tet", count: 123 },
	{ name: "Iranian (Other)", key: "/languages/ira", count: 119 },
	{ name: "Karen languages", key: "/languages/kar", count: 115 },
	{ name: "Ewe", key: "/languages/ewe", count: 112 },
	{ name: "Friulian", key: "/languages/fur", count: 111 },
	{ name: "Greenlandic", key: "/languages/kal", count: 111 },
	{ name: "Syriac", key: "/languages/syc", count: 110 },
	{ name: "Mon-Khmer (Other)", key: "/languages/mkh", count: 108 },
	{ name: "Sami", key: "/languages/smi", count: 107 },
	{ name: "Afroasiatic (Other)", key: "/languages/afa", count: 106 },
	{ name: "Samoan", key: "/languages/smo", count: 106 },
	{ name: "Mohawk", key: "/languages/moh", count: 105 },
	{ name: "Bemba", key: "/languages/bem", count: 104 },
	{ name: "Batak", key: "/languages/btk", count: 102 },
	{ name: "Achinese", key: "/languages/ace", count: 96 },
	{ name: "Minangkabau", key: "/languages/min", count: 96 },
	{ name: "Creoles and Pidgins, English-based (Other)", key: "/languages/cpe", count: 94 },
	{ name: "Abkhaz", key: "/languages/abk", count: 92 },
	{ name: "Algonquian (Other)", key: "/languages/alg", count: 92 },
	{ name: "Dutch, Middle (ca. 1050-1350)", key: "/languages/dum", count: 89 },
	{ name: "Old High German", key: "/languages/goh", count: 88 },
	{ name: "Filipino", key: "/languages/fil", count: 87 },
	{ name: "Low German", key: "/languages/nds", count: 83 },
	{ name: "Sumerian", key: "/languages/sux", count: 82 },
	{ name: "Cebuano", key: "/languages/ceb", count: 81 },
	{ name: "Ndonga", key: "/languages/ndo", count: 78 },
	{ name: "Western Pahari languages", key: "/languages/him", count: 77 },
	{ name: "Kongo", key: "/languages/kon", count: 77 },
	{ name: "Gikuyu", key: "/languages/kik", count: 73 },
	{ name: "Kumyk", key: "/languages/kum", count: 73 },
	{ name: "Creoles and Pidgins, Portuguese-based (Other)", key: "/languages/cpp", count: 72 },
	{ name: "G\u00e3", key: "/languages/gaa", count: 71 },
	{ name: "Kawi", key: "/languages/kaw", count: 70 },
	{ name: "Moor\u00e9", key: "/languages/mos", count: 70 },
	{ name: "Cherokee", key: "/languages/chr", count: 69 },
	{ name: "Gothic", key: "/languages/got", count: 68 },
	{ name: "Kachin", key: "/languages/kac", count: 67 },
	{ name: "Swiss German", key: "/languages/gsw", count: 65 },
	{ name: "Australian languages", key: "/languages/aus", count: 64 },
	{ name: "Dakota", key: "/languages/dak", count: 64 },
	{ name: "Karachay-Balkar", key: "/languages/krc", count: 64 },
	{ name: "Kirundi", key: "/languages/run", count: 64 },
	{ name: "Shan", key: "/languages/shn", count: 64 },
	{ name: "Iban", key: "/languages/iba", count: 63 },
	{ name: "Manobo languages", key: "/languages/mno", count: 63 },
	{ name: "Yupik languages", key: "/languages/ypk", count: 63 },
	{ name: "Iloko", key: "/languages/ilo", count: 61 },
	{ name: "Avestan", key: "/languages/ave", count: 59 },
	{ name: "Erzya", key: "/languages/myv", count: 58 },
	{ name: "Zaza", key: "/languages/zza", count: 57 },
	{ name: "Bikol", key: "/languages/bik", count: 56 },
	{ name: "Serer", key: "/languages/srr", count: 55 },
	{ name: "Tuvinian", key: "/languages/tyv", count: 55 },
	{ name: "Aymara", key: "/languages/aym", count: 53 },
	{ name: "Chagatai", key: "/languages/chg", count: 53 },
	{ name: "Indo-European (Other)", key: "/languages/ine", count: 53 },
	{ name: "Kurukh", key: "/languages/kru", count: 53 },
	{ name: "Micmac", key: "/languages/mic", count: 53 },
	{ name: "Pampanga", key: "/languages/pam", count: 53 },
	{ name: "Lezgian", key: "/languages/lez", count: 52 },
	{ name: "Songhai", key: "/languages/son", count: 52 },
	{ name: "Manchu", key: "/languages/mnc", count: 51 },
	{ name: "Munda (Other)", key: "/languages/mun", count: 50 },
	{ name: "Southern Ndebele", key: "/languages/nbl", count: 50 },
	{ name: "Judeo-Persian", key: "/languages/jpr", count: 49 },
	{ name: "Kabyle", key: "/languages/kab", count: 49 },
	{ name: "Interlingua", key: "/languages/ina", count: 48 },
	{ name: "Oirat", key: "/languages/xal", count: 48 },
	{ name: "Lingala", key: "/languages/lin", count: 47 },
	{ name: "Kwanyama", key: "/languages/kua", count: 46 },
	{ name: "Tamashek", key: "/languages/tmh", count: 46 },
	{ name: "Dargwa", key: "/languages/dar", count: 45 },
	{ name: "Cantonese", key: "/languages/yue", count: 44 },
	{ name: "Samaritan Aramaic", key: "/languages/sam", count: 43 },
	{ name: "Bugis", key: "/languages/bug", count: 42 },
	{ name: "Iroquoian (Other)", key: "/languages/iro", count: 42 },
	{ name: "Sinhalese", key: "/languages/snh", count: 42 },
	{ name: "Soninke", key: "/languages/snk", count: 42 },
	{ name: "Asturian", key: "/languages/ast", count: 41 },
	{ name: "Choctaw", key: "/languages/cho", count: 41 },
	{ name: "Northern Sami", key: "/languages/sme", count: 41 },
	{ name: "Dyula", key: "/languages/dyu", count: 40 },
	{ name: "Herero", key: "/languages/her", count: 40 },
	{ name: "Hmong", key: "/languages/hmn", count: 40 },
	{ name: "Makasar", key: "/languages/mak", count: 40 },
	{ name: "Tai", key: "/languages/tai", count: 38 },
	{ name: "Basa", key: "/languages/bas", count: 37 },
	{ name: "Celtic (Other)", key: "/languages/cel", count: 36 },
	{ name: "Moksha", key: "/languages/mdf", count: 36 },
	{ name: "Creek", key: "/languages/mus", count: 36 },
	{ name: "Khoisan (Other)", key: "/languages/khi", count: 35 },
	{ name: "Kpelle", key: "/languages/kpe", count: 35 },
	{ name: "Lozi", key: "/languages/loz", count: 34 },
	{ name: "Tigr\u00e9", key: "/languages/tig", count: 33 },
	{ name: "Akan", key: "/languages/aka", count: 32 },
	{ name: "Crimean Tatar", key: "/languages/crh", count: 32 },
	{ name: "Santali", key: "/languages/sat", count: 32 },
	{ name: "Zapotec", key: "/languages/zap", count: 32 },
	{ name: "Afar", key: "/languages/aar", count: 31 },
	{ name: "Manx", key: "/languages/glv", count: 31 },
	{ name: "Hiligaynon", key: "/languages/hil", count: 31 },
	{ name: "Tahitian", key: "/languages/tah", count: 31 },
	{ name: "Mapuche", key: "/languages/arn", count: 30 },
	{ name: "Fanti", key: "/languages/fat", count: 30 },
	{ name: "Luo (Kenya and Tanzania)", key: "/languages/luo", count: 30 },
	{ name: "Madurese", key: "/languages/mad", count: 30 },
	{ name: "Nogai", key: "/languages/nog", count: 29 },
	{ name: "Semitic (Other)", key: "/languages/sem", count: 29 },
	{ name: "Efik", key: "/languages/efi", count: 28 },
	{ name: "Karelian", key: "/languages/krl", count: 28 },
	{ name: "East Frisian", key: "/languages/frs", count: 27 },
	{ name: "Ingush", key: "/languages/inh", count: 27 },
	{ name: "Nyankole", key: "/languages/nyn", count: 27 },
	{ name: "Athapascan (Other)", key: "/languages/ath", count: 26 },
	{ name: "Fon", key: "/languages/fon", count: 26 },
	{ name: "Kru (Other)", key: "/languages/kro", count: 25 },
	{ name: "Vai", key: "/languages/vai", count: 25 },
	{ name: "Adangme", key: "/languages/ada", count: 24 },
	{ name: "Altai", key: "/languages/alt", count: 24 },
	{ name: "Chinook jargon", key: "/languages/chn", count: 24 },
	{ name: "Cushitic (Other)", key: "/languages/cus", count: 23 },
	{ name: "Mende", key: "/languages/men", count: 23 },
	{ name: "Old Persian (ca. 600-400 B.C.)", key: "/languages/peo", count: 23 },
	{ name: "Acoli", key: "/languages/ach", count: 22 },
	{ name: "Artificial (Other)", key: "/languages/art", count: 22 },
	{ name: "Navajo", key: "/languages/nav", count: 22 },
	{ name: "Aromanian", key: "/languages/rup", count: 22 },
	{ name: "Sango", key: "/languages/sag", count: 22 },
	{ name: "Gayo", key: "/languages/gay", count: 21 },
	{ name: "Old Norse", key: "/languages/non", count: 21 },
	{ name: "Palauan", key: "/languages/pau", count: 21 },
	{ name: "Marshallese", key: "/languages/mah", count: 20 },
	{ name: "Ponape", key: "/languages/pon", count: 20 },
	{ name: "Selkup", key: "/languages/sel", count: 20 },
	{ name: "Klingon", key: "/languages/tlh", count: 20 },
	{ name: "Salishan languages", key: "/languages/sal", count: 19 },
	{ name: "Tsimshian", key: "/languages/tsi", count: 19 },
	{ name: "Mongo-Nkundu", key: "/languages/lol", count: 18 },
	{ name: "Nzima", key: "/languages/nzi", count: 18 },
	{ name: "Bamileke languages", key: "/languages/bai", count: 17 },
	{ name: "Dayak", key: "/languages/day", count: 17 },
	{ name: "Elamite", key: "/languages/elx", count: 17 },
	{ name: "Luba-Katanga", key: "/languages/lub", count: 16 },
	{ name: "Tongan", key: "/languages/ton", count: 16 },
	{ name: "Apache languages", key: "/languages/apa", count: 15 },
	{ name: "Nyoro", key: "/languages/nyo", count: 15 },
	{ name: "Otomian languages", key: "/languages/oto", count: 15 },
	{ name: "Pangasinan", key: "/languages/pag", count: 15 },
	{ name: "Aragonese", key: "/languages/arg", count: 14 },
	{ name: "Delaware", key: "/languages/del", count: 14 },
	{ name: "Fijian", key: "/languages/fij", count: 14 },
	{ name: "Gondi", key: "/languages/gon", count: 14 },
	{ name: "Kamba", key: "/languages/kam", count: 14 },
	{ name: "Tonga (Nyasa)", key: "/languages/tog", count: 14 },
	{ name: "Waray", key: "/languages/war", count: 14 },
	{ name: "Ido", key: "/languages/ido", count: 13 },
	{ name: "Carib", key: "/languages/car", count: 12 },
	{ name: "Fang", key: "/languages/fan", count: 12 },
	{ name: "Sandawe", key: "/languages/sad", count: 12 },
	{ name: "Temne", key: "/languages/tem", count: 12 },
	{ name: "Aleut", key: "/languages/ale", count: 11 },
	{ name: "Siksika", key: "/languages/bla", count: 11 },
	{ name: "Chamorro", key: "/languages/cha", count: 11 },
	{ name: "Dinka", key: "/languages/din", count: 11 },
	{ name: "Tumbuka", key: "/languages/tum", count: 11 },
	{ name: "Ugaritic", key: "/languages/uga", count: 11 },
	{ name: "Yao (Africa)", key: "/languages/yao", count: 11 },
	{ name: "Edo", key: "/languages/bin", count: 10 },
	{ name: "Ewondo", key: "/languages/ewo", count: 10 },
	{ name: "Gilbertese", key: "/languages/gil", count: 10 },
	{ name: "Grebo", key: "/languages/grb", count: 10 },
	{ name: "Masai", key: "/languages/mas", count: 10 },
	{ name: "Inupiaq", key: "/languages/ipk", count: 9 },
	{ name: "Kanuri", key: "/languages/kau", count: 9 },
	{ name: "Tok Pisin", key: "/languages/tpi", count: 9 },
	{ name: "Cheyenne", key: "/languages/chy", count: 8 },
	{ name: "Lamba (Zambia and Congo)", key: "/languages/lam", count: 8 },
	{ name: "Lunda", key: "/languages/lun", count: 8 },
	{ name: "Mirandese", key: "/languages/mwl", count: 8 },
	{ name: "Nubian languages", key: "/languages/nub", count: 8 },
	{ name: "Rarotongan", key: "/languages/rar", count: 8 },
	{ name: "Sasak", key: "/languages/sas", count: 8 },
	{ name: "Arawak", key: "/languages/arw", count: 7 },
	{ name: "Bislama", key: "/languages/bis", count: 7 },
	{ name: "Chuukese", key: "/languages/chk", count: 7 },
	{ name: "Ijo", key: "/languages/ijo", count: 7 },
	{ name: "Kimbundu", key: "/languages/kmb", count: 7 },
	{ name: "Sidamo", key: "/languages/sid", count: 7 },
	{ name: "Siouan (Other)", key: "/languages/sio", count: 7 },
	{ name: "Arapaho", key: "/languages/arp", count: 6 },
	{ name: "Baltic (Other)", key: "/languages/bat", count: 6 },
	{ name: "Chamic languages", key: "/languages/cmc", count: 6 },
	{ name: "Duala", key: "/languages/dua", count: 6 },
	{ name: "Khotanese", key: "/languages/kho", count: 6 },
	{ name: "Sranan", key: "/languages/srn", count: 6 },
	{ name: "Tokelauan", key: "/languages/tkl", count: 6 },
	{ name: "Umbundu", key: "/languages/umb", count: 6 },
	{ name: "Flemish", key: "/languages/vls", count: 6 },
	{ name: "Zande languages", key: "/languages/znd", count: 6 },
	{ name: "Kusaie", key: "/languages/kos", count: 5 },
	{ name: "Sogdian", key: "/languages/sog", count: 5 },
	{ name: "Sukuma", key: "/languages/suk", count: 5 },
	{ name: "Tlingit", key: "/languages/tli", count: 5 },
	{ name: "Gorontalo", key: "/languages/gor", count: 4 },
	{ name: "Niuean", key: "/languages/niu", count: 4 },
	{ name: "Susu", key: "/languages/sus", count: 4 },
	{ name: "Tiv", key: "/languages/tiv", count: 4 },
	{ name: "Zuni", key: "/languages/zun", count: 4 },
	{ name: "Hiri Motu", key: "/languages/hmo", count: 3 },
	{ name: "Upper Sorbian", key: "/languages/hsb", count: 3 },
	{ name: "Luba-Lulua", key: "/languages/lua", count: 3 },
	{ name: "Terena", key: "/languages/ter", count: 3 },
	{ name: "Wakashan languages", key: "/languages/wak", count: 3 },
	{ name: "Wolayta", key: "/languages/wal", count: 3 },
	{ name: "American Sign Language", key: "/languages/ase", count: 2 },
	{ name: "Ekajuk", key: "/languages/eka", count: 2 },
	{ name: "Gbaya", key: "/languages/gba", count: 2 },
	{ name: "Gullah", key: "/languages/gul", count: 2 },
	{ name: "Osage", key: "/languages/osa", count: 2 },
	{ name: "Tuvaluan", key: "/languages/tvl", count: 2 },
	{ name: "Nauruan", key: "/languages/nau", count: 1 },
	{ name: "Yapese", key: "/languages/yap", count: 1 },
	{ name: "Khmer", key: "/languages/cam", count: 0 },
	{ name: "Esperanto", key: "/languages/esp", count: 0 },
	{ name: "Ethiopic", key: "/languages/eth", count: 0 },
	{ name: "Faroese", key: "/languages/far", count: 0 },
	{ name: "Frisian", key: "/languages/fri", count: 0 },
	{ name: "Scottish Gaelix", key: "/languages/gae", count: 0 },
	{ name: "Galician", key: "/languages/gag", count: 0 },
	{ name: "Oromo", key: "/languages/gal", count: 0 },
	{ name: "Guarani", key: "/languages/gua", count: 0 },
	{ name: "Interlingua (International Auxiliary Language Association)", key: "/languages/int", count: 0 },
	{ name: "Occitan (post 1500)", key: "/languages/lan", count: 0 },
	{ name: "Sami", key: "/languages/lap", count: 0 },
	{ name: "Malagasy", key: "/languages/mla", count: 0 },
	{ name: "Moldavian", key: "/languages/mol", count: 0 },
	{ name: "Samoan", key: "/languages/sao", count: 0 },
	{ name: "Shona", key: "/languages/sho", count: 0 },
	{ name: "Sotho", key: "/languages/sso", count: 0 },
	{ name: "Swazi", key: "/languages/swz", count: 0 },
	{ name: "Tagalog", key: "/languages/tag", count: 0 },
	{ name: "Tajik", key: "/languages/taj", count: 0 },
	{ name: "Tatar", key: "/languages/tar", count: 0 },
	{ name: "Tswana", key: "/languages/tsw", count: 0 },
]
